### ISSUE TITLE
How about that if we have Chinese version of this doc serial?

### ISSUE THREAD

**Issue by wenchunl** [IBM-Bluemix-Docs/apps#12]
I think it is important to have Chinese version of the docs, so that the developers and users from China can benefit, and obviously Improve visibility of IBM Cloud, and finally increase the market-share.

**Comment by christx83** [comment]
The IBM Cloud docs are translated into:
Chinese (Simplified)
Chinese (Traditional)

Go to https://cloud.ibm.com/user/ to see which language that your browser is detecting. 

To view content in your native language, update your browser's language settings.
