### ISSUE TITLE
Documentation not clear when a certificate must be renewed. 

### ISSUE THREAD

**Issue by araniolo** [IBM-Bluemix-Docs/apps#15]
In the following url:
https://cloud.ibm.com/docs/apps?topic=creating-apps-ssl_csr#ssl_csr
are described the following steps:
To upload a certificate for your Cloud Foundry app, complete the following steps:

    From the IBM Cloud console External link icon, click the Menu icon Menu icon, and select Resource List.
    Click Cloud Foundry Apps.
    Click the app that you want to change the domain for.
    On the app's Overview page, click Routes, and select Manage domains.
    From the Actions column, click the Actions icon More Actions icon, and select Domains.
    Click Upload for your custom domain.

    Select an option, upload the file, and click Add.

But, is not clear what to do when a certificate must be renewed. 
I would suggest to add a note saying:
Note: When an expired or expiring certificate must be renewed, once you have the new one ready you need to delete the existing one and add the new one.

**Comment by christx83** [comment]
Thank you for the feedback. We've updated the topic, and it is now available here:
https://cloud.ibm.com/docs/apps?topic=creating-apps-ssl_csr
