### ISSUE TITLE
the difference of CNAME registered domain

### ISSUE THREAD

**Issue by khayama** [IBM-Bluemix-Docs/apps#4]
What's the difference of CNAME registered domain between secure.au-syd.bluemix.net and appname.mybluemix.net for the routed custom domain access?

**Comment by khayama** [comment]
like this
![image](https://user-images.githubusercontent.com/13445142/45585965-7acf3e00-b929-11e8-8f49-5dd43f72bdcf.png)

**Comment by jpkessle** [comment]
@khayama 
The names are just arbitrary and must be unique to access your app. CNAME just means canonical name, which is just an alias hostname. In this case, you see that khayama.tk is a CNAME that points to the fully qualified secure.au-syd.bluemix.net and www is a CNAME which points to the fully qualified khayama-cf-js-1.au-syd.mybluemix.net.

What is a CNAME record? - DNSimple Help
https://support.dnsimple.com/articles/cname-record/

Please let me know if you have further questions.
Thank you,
Josh
